### ISSUE TITLE
Sticky List Look and Feel

### ISSUE THREAD

**Issue by Texasgirl22** [13pixlar/sticky-list#2]
I installed Sticky List. When you click on View, to view an item in  your list, the results are shown in the form that you created for listing (recipe.png attachment). Is there a way to just have the results appear differently (i.e. cake.png attachment, or a PDF file)? 

RECIPE.PNG
![recipe](https://cloud.githubusercontent.com/assets/11231552/6415262/e7ad8e44-be6b-11e4-9561-dd0bc9fe7c9b.png)

CAKE.PNG
![cake](https://cloud.githubusercontent.com/assets/11231552/6415268/f115d266-be6b-11e4-8da5-7776633c71a6.png)

Thank you!

**Comment by 13pixlar** [comment]
You could attach some post fields to your form so that every recipe is saved as a wordpress post. Then you can use the post link to show that post and you can style it however you like using css.

**Comment by Texasgirl22** [comment]
Ok. Thank you!

**Comment by 13pixlar** [comment]
No problem Texas Girl!
