### ISSUE TITLE
Missing files/folders and some functionalities doesn't work after updating to 1.5.2

### ISSUE THREAD

**Issue by kenvilar** [13pixlar/sticky-list#30]
After I updated the plugin to 1.5.2 version, the search and pagination functionalities does not work. When I checked the plugin folder, I noticed that there are some missing folders and files inside https://plugins.trac.wordpress.org/browser/gravity-forms-sticky-list/tags/1.5.2

![screen-shot](https://user-images.githubusercontent.com/2937299/53802841-d778f080-3f7d-11e9-9007-b2c616856138.png)

**Comment by 13pixlar** [comment]
Yes. Something was messed up with my last commit to the SVN repo. Please use the github version in the meanwhile.
