### ISSUE TITLE
Error After Editting Form - Payment Gateway Related

### ISSUE THREAD

**Issue by 1DayWebs** [13pixlar/sticky-list#8]
Hi there

I have a problem when a user edits their entry and pays again (via Gravity Forms PayFast Plugin), the payment gateway goes to a blank white screen after successful payment rather than passing back to the form.

The Payment Gateway developers say that the sticky list and sticky edit plugin is passing the return URL to the payment gateway so this is something you would need to look at, can you assist?

The log for the PayFast Add-on is here : http://cvcreator.1daywebs.xyz/wp-content/uploads/gravity_forms/logs/gravityformspayfast_1ee644071181821a74911fee280f9675c2cce9f3.txt

Kindly advise

**Comment by 13pixlar** [comment]
I'm sorry. I will not try to fix this. If your developers fixed this they can submit a pull request
